server:
  port: 10150

spring:
  application:
    name: sc-common
  profiles:
    active: dev
#  config:
#    import[0]: nacos:sc-common.yaml?group=DEFAULT_GROUP
#    import[1]: nacos:mybatis-plus.yaml?group=DEFAULT_GROUP
#  #    spring.config.import[1]=nacos:{dataId1}?group={group1}
#  cloud:
#    nacos:
#      config:
#        namespace: ede3834d-0b93-4b3b-960d-0f656975cc1d
#        server-addr: 127.0.0.1:8848
